In [8]:
import numpy as np
import pandas as pd

cafe_sales = pd.read_csv('dirty_cafe_sales.csv', na_values=['UNKNOWN', 'ERROR', ' '])
cafe_sales['Transaction Date'] = pd.to_datetime(cafe_sales['Transaction Date'])

print(cafe_sales.isna().sum())

cafe_sales.head(20)

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15

In [10]:
cafe_sales['Price Per Unit'].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5, nan])

In [ ]:
cafe_sales['Total Spent'] = cafe_sales['Total Spent'].fillna(cafe_sales['Quantity']*cafe_sales['Price Per Unit'])
cafe_sales['Quantity'] = cafe_sales['Quantity'].fillna(cafe_sales['Total Spent']/cafe_sales['Price Per Unit'])
cafe_sales['Price Per Unit'] = cafe_sales['Price Per Unit'].fillna(cafe_sales['Total Spent']/cafe_sales['Quantity'])

print(cafe_sales.isna().sum())

Transaction ID         0
Item                 969
Quantity              38
Price Per Unit        38
Total Spent           40
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,5.0,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.0,4.0,12.0,NaN,NaN,2023-12-13
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,NaT
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,NaN,2.0,1.0,2.0,Credit Card,NaN,2023-11-06
32,TXN_9677376,Smoothie,4.0,4.0,16.0,NaN,In-store,2023-08-15
33,TXN_7710508,NaN,5.0,1.0,5.0,Cash,NaN,NaT
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,NaN,2023-05-28
36,TXN_6855453,NaN,4.0,3.0,12.0,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.0,4.0,16.0,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.0,2.0,8.0,NaN,NaN,2023-06-29

In [12]:
cafe_sales['Item'].dropna().unique()

price = cafe_sales['Price Per Unit'].dropna().sort_values().unique()

for i in price:
    items = cafe_sales.loc[cafe_sales['Price Per Unit'] == i, 'Item'].unique()
    print(i, items)

1.0 <StringArray>
['Cookie', nan]
Length: 2, dtype: str
1.5 <StringArray>
[nan, 'Tea']
Length: 2, dtype: str
2.0 <StringArray>
['Coffee', nan]
Length: 2, dtype: str
3.0 <StringArray>
['Cake', nan, 'Juice']
Length: 3, dtype: str
4.0 <StringArray>
['Smoothie', 'Sandwich', nan]
Length: 3, dtype: str
5.0 <StringArray>
['Salad', nan]
Length: 2, dtype: str

In [13]:
def filling_na_price (df, x, y):
    df.loc[df['Price Per Unit'] == x, 'Item'] = df.loc[df['Price Per Unit'] == x, 'Item'].fillna(y)

items_prices = {
    'Cookie' : 1.0,
    'Tea' : 1.5,
    'Coffee' : 2.0,
    'Salad' : 5.0
}

for item, price in items_prices.items():
    filling_na_price(cafe_sales, price, item)


# def filling_items(df, x, y):
#     mask = (df['Price Per Unit'] == x) & (df['Item'].isna())
#     n = mask.sum()
#     if n > 0:
#         df.loc[mask, 'Item'] = np.random.choice(y, size=n)

In [ ]:
cafe_sales.to_csv('cleaned_cafe_sales_dataset.csv', index=False)